rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=2.7.22
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.22
notifications:
  email: false

# vim: set ts=2 sw=2 et ft=yaml:
